AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation for creating a S3 bucket'

Resources:
  TerraformStateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: s3-bucket-nst-delete
      VersioningConfiguration:
        Status: Enabled

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref TerraformStateBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowSSEPut'
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::s3-bucket-nst-delete/*'
            Condition:
              StringEquals:
                's3:x-amz-server-side-encryption': 'AES256'
