AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template to create an IAM role for project-specific management'

Resources:
  ProjectManagementRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'ROLE_NAME_PLACEHOLDER'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Federated: 'OIDC_PROVIDER_ARN'
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringLike: {
                 "OIDC_PROVIDER_DOMAIN:sub": [
                    "project_path:PROJECT_PATH_1:ref_type:branch:ref:main",
                    "project_path:PROJECT_PATH_2:ref_type:branch:ref:main",
                    "project_path:PROJECT_PATH_3:*"
                 ]
              }
      Policies:
        - PolicyName: 'ProjectSpecificManagementPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:CreateBucket'
                  - 's3:DeleteBucket'
                  - 's3:ListBucket'
                  - 's3:GetBucketLocation'
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                Resource: '*'

Outputs:
  RoleARN:
    Description: 'ARN of the created IAM Role'
    Value: !GetAtt ProjectManagementRole.Arn
